Bahmni/implementer-interface

src/form-builder/components/ControlPropertiesContainer.jsx
src/form-builder/components/ControlReduxWrapper.jsx
src/form-builder/components/PropertyEditor.jsx
test/form-builder/components/ControlPropertiesContainer.spec.js
test/form-builder/components/ControlReduxWrapper.spec.js

1. Add-more property added for section.
2. Use the published form-controls package from https://github.com/Bahmni/form-controls/pull/3
3. JIRA: https://bahmni.atlassian.net/browse/BAH-740

Add More Ability For a Section within a Form

---

src/form-builder/components/FormDetailContainer.jsx
src/form-builder/components/PropertyEditor.jsx
src/form-builder/constants.js
src/form-builder/reducers/translations.js
test/form-builder/components/FormDetailContainer.spec.js
test/form-builder/components/PropertyEditor.spec.js
test/form-builder/reducers/translations.spec.js

1. Filter out unsupported control in table control
2. Needs the form-control PR - https://github.com/Bahmni/form-controls/pull/4 to be merged & published.
3. JIRA: https://bahmni.atlassian.net/browse/BAH-748

[Form Builder] Create and render a table inside form

---

src/form-builder/actions/control.js
src/form-builder/components/Canvas.jsx
src/form-builder/components/ControlReduxWrapper.jsx
src/form-builder/components/DeleteControlModal.jsx
src/form-builder/helpers/dragDropHelper.js
src/form-builder/reducers/controlDetails.js
test/form-builder/components/Canvas.spec.js
test/form-builder/components/ControlReduxWrapper.spec.js
test/form-builder/components/DeleteControlModal.spec.js
test/form-builder/helpers/dragDropHelper.spec.js

**Fixes the following:**
1.  Do not allow to drag and drop controls to obsGroup (https://bahmni.atlassian.net/browse/BAH-133)
2. Dragging a section inside an inner section causes the entire section to vanish (https://bahmni.atlassian.net/browse/BAH-831)
3. Controls will be deleted by deleting other control(https://bahmni.atlassian.net/browse/BAH-831)
**Note:** 
1. Should be merged after the PR https://github.com/Bahmni/form-controls/pull/6 has been merged and new form-controls package has been published.
2. The new version of form-controls published, needs to be consumed for this to work correctly.

Sneha | BAH-133 & BAH-831 | Drag drop fix

---

src/form-builder/components/FormDetailContainer.jsx
test/form-builder/components/FormDetailContainer.spec.js

Add reference version to get the translations.
Bahmni jira link:
https://bahmni.atlassian.net/browse/BAH-866

#BAH-866 | Translations to be copied from one version to next version

---

package.json
src/common/constants.js
src/form-builder/components/FormBuilder.jsx
src/form-builder/components/FormList.jsx
src/form-builder/constants.js
styles/common/_form.scss
styles/common/_formList.scss
styles/common/_notification.scss
test/form-builder/components/FormBuilder.spec.js
test/form-builder/components/FormList.spec.js

User should be able to export multiple forms from form builder

#BAH-912 | Export multiple forms in form builder 

---

src/form-builder/actions/control.js
src/form-builder/components/ControlReduxWrapper.jsx
src/form-builder/components/FormDetail.jsx
src/form-builder/components/FormDetailContainer.jsx
src/form-builder/components/FormEventContainer.jsx
src/form-builder/reducers/formDetails.js
test/form-builder/actions/control.spec.js
test/form-builder/components/ControlReduxWrapper.spec.js
test/form-builder/components/FormDetail.spec.js
test/form-builder/components/FormEventContainer.spec.js
test/form-builder/reducers/formDetails.spec.js

[BAH-1010](https://bahmni.atlassian.net/browse/BAH-1010)

BAH-1010 | Create event editor to provide onSave eventhandler

---

package.json
src/form-builder/components/ControlReduxWrapper.jsx
src/form-builder/components/FormBuilder.jsx
src/form-builder/components/FormBuilderContainer.jsx
src/form-builder/components/FormDetail.jsx
src/form-builder/components/FormEventEditor.jsx
src/form-builder/components/ScriptEditorModal.js
src/form-builder/reducers/translations.js
styles/common/_bahmniGlobal.scss
styles/common/_canvas.scss
styles/common/_popUp.scss
test/form-builder/components/ControlReduxWrapper.spec.js
test/form-builder/components/FormBuilder.spec.js
test/form-builder/components/FormDetail.spec.js
test/form-builder/components/FormDetailContainer.spec.js
test/form-builder/components/FormEventEditor.spec.js
test/form-builder/reducers/translations.spec.js
yarn.lock

[BAH - 1016](https://bahmni.atlassian.net/browse/BAH-1016)

BAH - 1016 | Ui enhancements pr

---

src/form-builder/components/FormDetailContainer.jsx
src/form-builder/components/FormPreviewModal.jsx
styles/common/_form.scss
styles/common/_popUp.scss
test/form-builder/components/FormDetail.spec.js
test/form-builder/components/FormDetailContainer.spec.js
test/form-builder/components/FormPreviewModal.spec.js

https://bahmni.atlassian.net/browse/BAH-1017

BAH-1017 | Preview and onSave event error handling

---

src/common/apis/formPrivilegesApi.js
src/form-builder/actions/control.js
src/form-builder/components/FormBuilderBreadcrumbs.jsx
src/form-builder/components/FormDetail.jsx
src/form-builder/components/FormDetailContainer.jsx
src/form-builder/components/FormEventEditor.jsx
src/form-builder/components/FormList.jsx
src/form-builder/components/FormPrivilegeTable.jsx
src/form-builder/components/FormPrivilegesContainer.jsx
src/form-builder/components/FormPrivilegesEditorModal.jsx
src/form-builder/components/FormPrivilegesPreviewContainer.jsx
src/form-builder/components/FormPrivilegesPreviewGrid.jsx
src/form-builder/constants.js
src/form-builder/helpers/UrlHelper.js
src/form-builder/reducers/formDetails.js
src/form-builder/reducers/formPrivileges.js
src/form-builder/reducers/index.js
src/index.js
styles/_home.scss
styles/common/_bahmniGlobal.scss
styles/common/_form.scss
styles/common/_popUp.scss
test/form-builder/components/FormEventEditor.spec.js
test/form-builder/components/FormList.spec.js
test/form-builder/components/FormPrivilegeTable.spec.js

https://bahmni.atlassian.net/browse/BAH-790
https://bahmni.atlassian.net/browse/BAH-995
ttps://bahmni.atlassian.net/browse/BAH-997
https://bahmni.atlassian.net/browse/BAH-998
https://bahmni.atlassian.net/browse/BAH-1001
https://bahmni.atlassian.net/browse/BAH-1002

BAH 790 - Role/Privilege based access to forms. Implementer interface side fixes.

---

src/common/apis/formPrivilegesApi.js
src/form-builder/components/FormDetail.jsx
src/form-builder/components/FormDetailContainer.jsx
src/form-builder/components/FormList.jsx
src/form-builder/components/FormPrivilegeTable.jsx
src/form-builder/components/FormPrivilegesContainer.jsx
src/form-builder/components/FormPrivilegesEditorModal.jsx
src/form-builder/components/FormPrivilegesPreviewContainer.jsx
src/form-builder/components/FormPrivilegesPreviewGrid.jsx
src/form-builder/constants.js
src/form-builder/helpers/UrlHelper.js
src/form-builder/reducers/formDetails.js
src/form-builder/reducers/formPrivileges.js
src/form-builder/reducers/index.js
src/index.js
styles/_home.scss
styles/common/_popUp.scss
test/form-builder/components/FormPrivilegeTable.spec.js

All conflicts have been removed and the PR has been raised.

BAH-790|Buvaneswari| Implementer Interface changes UI - Final Clean Version

---

src/form-builder/components/FormDetailContainer.jsx
test/form-builder/components/FormDetailContainer.spec.js
test/form-builder/components/FormList.spec.js
test/form-builder/components/FormPrivilegeTable.spec.js
test/form-builder/components/FormPrivilegesPreviewGrid.spec.js

A minor change is done to file FileDetailContainer where the forms privileges of parent form is applied to children is modified.

Bah 790 final - Testcases fixes - CI failure.

---

karma.conf.js
src/form-builder/components/FormBuilderBreadcrumbs.jsx
src/index.js

https://bahmni.atlassian.net/browse/BAH-1114

Bindu | BAH-1114 | Form Privileges grid - bread crumbs not properly rendered

---

.github/workflows/build_publish.yml

Fixes Helm release commit message happening to helm-charts repository

Fix. Helm release commit message

---

src/form-builder/components/FormBuilderHeader.jsx

JIRA- [https://bahmni.atlassian.net/browse/BAH-2411](https://bahmni.atlassian.net/browse/BAH-2411)

BAH-2411 | Updating home button link in Implementer Interface

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml

Co-authored-by: Siva Reddy <sivareddy.pathuri@thoughtworks.com>
JIRA https://bahmni.atlassian.net/browse/BS-39
Published Images Screenshot

BS-39 | Siva,Vijay | Publish implementer-interface with SNOMED image tags

---

README.md

Add SNOMED integration support in README
https://bahmni.atlassian.net/browse/BS-113

Add SNOMED integration support in README

---

package.json
yarn.lock

JIRA => https://bahmni.atlassian.net/browse/BS-108

BS-108 | Bahmni Form Controls version upgrade to 0.93.11-snomed.1

---

src/form-builder/components/Property.jsx
test/form-builder/components/Property.spec.js

Form builder URL doing a lookup for every keystroke, throwing errors for incomplete URLs, However, copy pasting URL works
https://bahmni.atlassian.net/browse/BS-135

Add onBlur attribute to URL control 

---

src/form-builder/components/Property.jsx
test/form-builder/components/Property.spec.js

BS-135 | Patrick | Fix for Form Builder  URL field not able to type on the fly

Add onBlur attribute to URL control  (#99)

---

package.json
yarn.lock

JIRA https://bahmni.atlassian.net/browse/BAH-3109

BAH-3109 | Bump up form controls version

---

package.json
yarn.lock

JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?selectedIssue=BAH-3700
Bumping up bahmni-form-controls package in implementer interface

BAH-3700 | Autocomplete Dropdown field with Multiselect acting flaky after selecting a value

---

package.json

JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.

BAH-4097 | Add. Bump Version Number In package.json

---

package.json

BAH-4113 | Add. Bump Version Number In package.json

---

karma.conf.js
src/form-builder/components/FormPrivilegeTable.jsx
src/form-builder/components/FormPrivilegesEditorModal.js

A published form can't be assigned privilege without editing and creating a new version first

BAH-4201 | Fixing pagination issue and also restricting privilege assigned if the form is published. 
